// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptzuijpjmqogcvigvklv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0enVpanBqbXFvZ2N2aWd2a2x2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYzODExMDQsImV4cCI6MjA4MTk1NzEwNH0.SPBb2JdSkgWF5npR_E-K0FshikeCpYk5CWL6PhQUKzs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
